version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx_API_Aggregator
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/cert:/etc/cert
    ports:
      - 2053:2053
    networks:
      - interconnector
networks:
  interconnector:
    driver: bridge